name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: comethrusws
          template: classic
          base: ""
          config_timezone: Asia/Katmandu
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year